name: Output Secret Value

on:
  workflow_dispatch:  # This allows manual trigger of the workflow

jobs:
  print-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Output secret value
        run: |
          echo "The value of the secret is: ${{ secrets.MY_SECRET }}"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
