name: Test Secret Masking

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-secret-masking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print secret with spaces
        run: |
          echo "Printing the secret with spaces:"
          echo ${{ secrets.MY_SECRET }} | sed 's/./&'
